import { useEffect, useMemo, useState } from 'react';
import { Building2, Filter, Mail, MapPin, MoreHorizontal, Phone, Plus, Search, Users, X } from 'lucide-react';
import { useApp } from '../contexts/AppContext';
import { supabase } from '../lib/supabase';

type Customer = { id:string; name:string; legal_name?:string; document?:string; email?:string; phone?:string; city?:string; state?:string; status:string; segment?:string };
const demo: Customer[] = [
  {id:'c1',name:'Mercado Central',legal_name:'Mercado Central Alimentos Ltda.',document:'12.345.678/0001-90',email:'compras@mercadocentral.com.br',phone:'(11) 3123-4400',city:'São Paulo',state:'SP',status:'Ativo',segment:'Varejo'},
  {id:'c2',name:'Clima Sul',legal_name:'Clima Sul Refrigeração Ltda.',document:'27.991.114/0001-22',email:'comercial@climasul.com.br',phone:'(41) 3022-7711',city:'Curitiba',state:'PR',status:'Ativo',segment:'Distribuidor'},
  {id:'c3',name:'Hotel Atlântico',legal_name:'Atlântico Hotelaria S.A.',document:'44.201.700/0001-08',email:'manutencao@atlantico.com.br',phone:'(21) 3555-9090',city:'Rio de Janeiro',state:'RJ',status:'Prospect',segment:'Hotelaria'},
  {id:'c4',name:'FrioMax',legal_name:'FrioMax Equipamentos Ltda.',document:'33.882.778/0001-55',email:'contato@friomax.com.br',phone:'(19) 3234-7001',city:'Campinas',state:'SP',status:'Ativo',segment:'Revenda'}
];
export function Customers(){
 const {activeCompany,demoMode}=useApp(); const [items,setItems]=useState<Customer[]>(demo); const [query,setQuery]=useState(''); const [open,setOpen]=useState(false);
 useEffect(()=>{ if(!supabase||demoMode||!activeCompany) return; void supabase.from('customers').select('id,name,legal_name,document,email,phone,status,customer_addresses(city,state)').eq('company_id',activeCompany.id).is('deleted_at',null).then(({data})=>setItems((data??[]).map((x:any)=>({...x,city:x.customer_addresses?.[0]?.city,state:x.customer_addresses?.[0]?.state,status:x.status==='active'?'Ativo':'Inativo'})))); },[activeCompany,demoMode]);
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.legal_name} ${x.document} ${x.city}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const item:Customer={id:crypto.randomUUID(),name:String(fd.get('name')),legal_name:String(fd.get('legal_name')),document:String(fd.get('document')),email:String(fd.get('email')),phone:String(fd.get('phone')),city:String(fd.get('city')),state:String(fd.get('state')),status:'Ativo',segment:String(fd.get('segment'))}; setItems(v=>[item,...v]); setOpen(false)};
 return <><div className="page-header"><div><span className="eyebrow">Relacionamento</span><h1>Clientes</h1><p>Gerencie sua carteira, contatos e histórico comercial por empresa.</p></div><button className="primary-button compact" onClick={()=>setOpen(true)}><Plus/> Novo cliente</button></div>
 <div className="module-stats"><div><Users/><span><small>Total de clientes</small><strong>{items.length}</strong></span></div><div><Building2/><span><small>Clientes ativos</small><strong>{items.filter(x=>x.status==='Ativo').length}</strong></span></div><div><MapPin/><span><small>Estados atendidos</small><strong>{new Set(items.map(x=>x.state)).size}</strong></span></div></div>
 <section className="module-card"><div className="module-toolbar"><div className="module-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, CNPJ, cidade..."/></div><button className="secondary-button"><Filter/> Filtros</button></div>
 <div className="customer-list"><div className="list-head"><span>Cliente</span><span>Contato</span><span>Localização</span><span>Status</span><span></span></div>{filtered.map(c=><div className="customer-row" key={c.id}><div className="entity-cell"><div className="entity-avatar">{c.name.slice(0,2).toUpperCase()}</div><span><strong>{c.name}</strong><small>{c.document||c.legal_name}</small></span></div><div><strong className="row-main"><Mail/> {c.email}</strong><small><Phone/> {c.phone}</small></div><div><strong className="row-main"><MapPin/> {c.city} - {c.state}</strong><small>{c.segment}</small></div><div><em className={`status-tag ${c.status==='Prospect'?'prospect':''}`}>{c.status}</em></div><button className="row-menu"><MoreHorizontal/></button></div>)}</div></section>
 {open&&<div className="modal-backdrop"><form className="modal-card" onSubmit={add}><div className="modal-head"><div><span className="eyebrow">Novo cadastro</span><h2>Adicionar cliente</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="form-grid"><label className="span-2">Nome fantasia<input name="name" required/></label><label className="span-2">Razão social<input name="legal_name"/></label><label>CNPJ<input name="document"/></label><label>Segmento<input name="segment"/></label><label>E-mail<input name="email" type="email"/></label><label>Telefone<input name="phone"/></label><label>Cidade<input name="city"/></label><label>Estado<input name="state" maxLength={2}/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button compact">Salvar cliente</button></div></form></div>}</>;
}
